version: '3'

services:
  icat:
    build:
      context: ../../catalogs/postgres-10.12
      args:
        postgres_password: testpassword
    hostname: catalog.example.org
    networks:
      default:
        aliases:
          - catalog.example.org

  irods-catalog-provider:
    build:
      context: provider
    hostname: icat.example.org
    networks:
      default:
        aliases:
          - icat.example.org
    depends_on:
      - icat

  irods-catalog-consumer-resource1:
    build:
      context: consumer
    hostname: resource1.example.org
    networks:
      default:
        aliases:
          - resource1.example.org
    depends_on:
      - irods-catalog-provider

  irods-catalog-consumer-resource2:
    build:
      context: consumer
    hostname: resource2.example.org
    networks:
      default:
        aliases:
          - resource2.example.org
    depends_on:
      - irods-catalog-provider

  irods-catalog-consumer-resource3:
    build:
      context: consumer
    hostname: resource3.example.org
    networks:
      default:
        aliases:
          - resource3.example.org
    depends_on:
      - irods-catalog-provider
